FROM debian:stable-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        squashfs-tools \
        grub-pc-bin \
        grub-efi-amd64-bin \
        xorriso \
        sudo \
        mount \
        qemu-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /work
